services:
  postgres:
    image: postgres:16-alpine
    container_name: deepsea-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: deepsea
      POSTGRES_PASSWORD: deepsea
    volumes:
      - deepsea-postgres-data:/var/lib/postgresql/data
      - ./docker/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    ports:
      - "5432:5432"
    networks:
      - deepsea-network

networks:
  deepsea-network:
    driver: bridge

volumes:
  deepsea-postgres-data:
    driver: local
